name: loveliz_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  get_it: ^8.0.3
  awesome_snackbar_content: ^0.1.5
  dartz: ^0.10.1
  http: ^1.2.2
  shared_preferences: ^2.3.5
  jwt_decoder: ^2.0.1
  dio: ^5.8.0+1
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  flutter_barcode_scanner_plus: ^3.0.8
  dropdown_search: ^6.0.2
  asuka: ^2.2.1
  animated_toggle_switch: ^0.8.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
